export const AUTH_START               = 'AUTH_START';
export const AUTH_SUCCESS             = 'AUTH_SUCCESS';
export const AUTH_FAIL                = 'AUTH_FAIL';
export const AUTH_LOGOUT              = 'AUTH_LOGOUT';

export const CONNECT_START               = 'CONNECT_START';
export const CONNECT_SUCCESS             = 'CONNECT_SUCCESS';
export const CONNECT_FAIL                = 'CONNECT_FAIL';
export const CONNECT_LOGOUT              = 'CONNECT_LOGOUT';

export const FB_AUTH_START            = 'FB_AUTH_START';
export const FB_AUTH_SUCCESS          = 'FB_AUTH_SUCCESS';
export const FB_AUTH_FAIL             = 'FB_AUTH_FAIL';
export const FB_AUTH_LOGOUT           = 'FB_AUTH_LOGOUT';

export const NEW_ADDRESS_START        = 'NEW_ADDRESS_START';
export const NEW_ADDRESS_SUCCESS      = 'NEW_ADDRESS_SUCCESS';
export const NEW_ADDRESS_FAIL         = 'NEW_ADDRESS_FAIL';
export const NEW_ADDRESS              = 'NEW_ADDRESS';


export const SET_AUTH_REDIRECT_PATH   = 'SET_AUTH_REDIRECT_PATH';


export const DELETE_USER_START = 'DELETE_USER_START'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'
export const DELETE_USER = 'DELETE_USER'

export const NEW_USER_START = 'NEW_USER_START'
export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS'
export const NEW_USER_FAIL = 'NEW_USER_FAIL'
export const NEW_USER = 'NEW_USER'
export const SET_NEW_USER_REDIRECT_PATH = 'SET_NEW_USER_REDIRECT_PATH'

export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'
export const FETCH_USER = 'FETCH_USER'

export const UPDATE_USER_START = 'UPDATE_USER_START'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
export const UPDATE_USER = 'UPDATE_USER'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const SET_LOGIN_REDIRECT_PATH = 'SET_LOGIN_REDIRECT_PATH'

export const NEW_POST_START = 'NEW_POST_START'
export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS'
export const NEW_POST_FAIL = 'NEW_POST_FAIL'
export const NEW_POST = 'NEW_POST'

export const SET_NEW_POST_REDIRECT_PATH = 'SET_NEW_POST_REDIRECT_PATH'

export const NEW_POST_INIT = 'NEW_POST_INIT'

export const FETCH_POSTS_START = 'FETCH_POSTS_START'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL'
export const FETCH_POSTS = 'FETCH_POSTS'

export const FETCH_POSTS_BY_ID_START = 'FETCH_POSTS_BY_ID_START'
export const FETCH_POSTS_BY_ID_SUCCESS = 'FETCH_POSTS_BY_ID_SUCCESS'
export const FETCH_POSTS_BY_ID_FAIL = 'FETCH_POSTS_BY_ID_FAIL'
export const FETCH_POSTS_BY_ID = 'FETCH_POSTS_BY_ID'

export const DELETE_POST_START = 'DELETE_POST_START'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'
export const DELETE_POST = 'DELETE_POST'

export const FETCH_POSTS_BY_YEAR_START = 'FETCH_POSTS_BY_YEAR_START'
export const FETCH_POSTS_BY_YEAR_SUCCESS = 'FETCH_POSTS_BY_YEAR_SUCCESS'
export const FETCH_POSTS_BY_YEAR_FAIL = 'FETCH_POSTS_BY_YEAR_FAIL'
export const FETCH_POSTS_BY_YEAR = 'FETCH_POSTS_BY_YEAR'

export const FETCH_POSTS_BY_MONTH_START = 'FETCH_POSTS_BY_MONTH_START'
export const FETCH_POSTS_BY_MONTH_SUCCESS = 'FETCH_POSTS_BY_MONTH_SUCCESS'
export const FETCH_POSTS_BY_MONTH_FAIL = 'FETCH_POSTS_BY_MONTH_FAIL'
export const FETCH_POSTS_BY_MONTH = 'FETCH_POSTS_BY_MONTH'

export const GET_USER_START = 'GET_USER_START'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAIL = 'GET_USER_FAIL'
export const GET_USER = 'GET_USER'